### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by Jdjrhs** [Yutixcode/Kangspam#3]
Can't run in termux and cmd, the code is Traceback (most recent call last):
  File "kangspam5.py", line 1, in <module>
  File "(Mengentot)", line 1, in <module>
  File "<string>", line 954, in <module>
  File "<string>", line 133, in main
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by ramdan8** [comment]
Cara menjalankan nya gimana

**Comment by Yutixcode** [comment]
> Cara menjalankan nya gimana

lg mainten blm bsa djalanin lg

**Comment by ramdan8** [comment]
Ouh iya udah siap

Pada tanggal Jum, 8 Des 2023 17.55, Yutixcode ***@***.***>
menulis:
